version: '3'

services:
  server-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    environment:
      PORT: 8080
      SECRET_KEY: secretKey
      LOG_FORMAT: dev
      LOG_DIR: ../logs
      ORIGIN: http://localhost:3000
      CREDENTIALS: true
      DIR_PLACEMENT: docker
      NODE_ENV: development
      DOMEN: http://localhost:8080
      DATABASE_URL: mysql://root:root@db-node:3306/testovoe?schema=public
    volumes:
      - ./:/var/www
    ports:
      - 8080:8080
    depends_on:
      db-node:
        condition: service_healthy
    tty: true


  db-node:
    image: mysql
    restart: always
    hostname: mysql
    container_name: db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 15s
      retries: 10
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testovoe
      MYSQLX: OFF
    ports:
      - 3307:3306

